<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<?php
$script = <<<JS

require(['jquery'], function ($) {

    const shouldLoadQuoteData = window.taggersEventsConfig
        && window.taggersEventsConfig.remove_from_cart === true;

    $(document).on('ajax:addToCart', function (event, data) {
        taggrsAjaxEvent('addtocart').then(() => {
            if (shouldLoadQuoteData) {
                taggrsReloadQuoteData();
            }
        });
    });

    $("[data-block=\"minicart\"]").on("dropdowndialogopen", function ( e ) {
        if (shouldLoadQuoteData) {
            taggrsReloadQuoteData();
        }
        taggrsAjaxEvent('viewcart', () => {}, 1);
    });
});

JS;
?>

<?= /* @noEscape */ $secureRenderer->renderTag('script', ['type' => 'text/javascript'], $script, false); ?>
