<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<?php
$script = <<<JS

require(['jquery'], function ($) {

    $(document).on('ajax:addToCart', function (event, data) {
        taggrsAjaxEvent('addtocart').then(() => {
            taggrsReloadQuoteData();
        });
    });

    $("[data-block=\"minicart\"]").on("dropdowndialogopen", function ( e ) {
        taggrsAjaxEvent('viewcart', () => {}, 1);
    });
});

JS;
?>

<?= /* @noEscape */ $secureRenderer->renderTag('script', ['type' => 'text/javascript'], $script, false); ?>
