<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<script>
    require(['jquery'], function ($) {

        $(document).on('ajax:addToCart', function (event, data) {
            taggrsAjaxEvent('addtocart').then(() => {
                taggrsReloadQuoteData();
            });
        });

        $("[data-block=\"minicart\"]").on("dropdowndialogopen", function ( e ) {
            taggrsAjaxEvent('viewcart', () => {}, 1);
        });
    });
</script>
