<script>
    require([
            'Magento_SalesRule/js/action/set-coupon-code',
            'Magento_SalesRule/js/model/coupon',
            'Magento_Checkout/js/model/quote'
        ],
        function (setCouponCode, coupon, quote) {
            console.log(setCouponCode);
            setCouponCode.registerSuccessCallback((response) => {
                console.log("GREAT SUCCESS!")
                console.log(quote);
                console.log(coupon.getCouponCode()._latestValue);
                taggrsAjaxEvent('selectpromotion');
            });
        });
</script>
