<?php
/** @var \Taggrs\DataLayer\Block\DataLayer $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$jsonDatalayer =  /* @noEscape */ json_encode($block->getDataLayer());
?>

<?php
$script = <<<JS

(function () {
    document.addEventListener('DOMContentLoaded', () => {
        const dataLayer = $jsonDatalayer;
        taggrsPush(dataLayer, true);
    });
})();

JS;
?>

<?= /* @noEscape */ $secureRenderer->renderTag('script', ['type' => 'text/javascript'], $script, false); ?>
